name: push docker image to dockerhub
on: 
 push:

jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
    - uses: actions/checkout@v1
    - name: Build and tag image 
      run: docker build -t "zhu5201314/dockercontainer_action:1.4.0" -f Dockerfile .

   

    - name: run
      run: |
         docker run zhu5201314/dockercontainer_action:1.4.0 

    #docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

    #docker push docker.pkg.github.com/zhuorg/newdocker/docker-learn:$GITHUB_SHA  



    - name: Docker login 
      run: docker login -u yanjingzhu -p $dockerhub_pw 
      env: 
        dockerhub_pw: ${{secrets.DHPW}} 



    - name: Publish to GPR 
      run: docker push "zhu5201314/dockercontainer_action:1.4.0"
